### ISSUE TITLE
Not working on death

### ISSUE THREAD

**Issue by ZanEtherial** [Frogworks-Interactive/OOF#3]
At the moment seems oof does not play on death, either own or others
This is happening in DT content, i don't know in older content.

**Comment by Kenzifer** [comment]
It doesn't seem to be working in any content.

**Comment by codelastnight** [comment]
oh naur... I am gonna investigate this

**Comment by codelastnight** [comment]
https://github.com/goatcorp/DalamudPluginsD17/pull/4073

pushed a change tonight that shouldddd fix this

**Comment by codelastnight** [comment]
fixed
