### ISSUE TITLE
Any news on updating this for 7.11?

### ISSUE THREAD

**Issue by Michelzinn** [Frogworks-Interactive/OOF#4]
my life depends on this plugin

**Comment by ActionHOSchT** [comment]
the slight smile while savage-practice is gone... pls consider updating this and bringing back the joy of failure.

**Comment by codelastnight** [comment]
the people have spoken...

**Comment by codelastnight** [comment]
🫡 update will be live when this PR is merged https://github.com/goatcorp/DalamudPluginsD17/pull/5156
